### ISSUE TITLE
Move this project to OCA

### ISSUE THREAD

**Issue by pedrobaeza** [prestapyt/prestapyt#36]
@guewen, do you think this project can be under OCA umbrella?

**Comment by guewen** [comment]
Two-folds answers:

* From the prestapyt side, I have no problem with moving it under the OCA umbrella, in fact, from long ago I can't maintain it. That's why I already created a `prestapyt` github org and am looking for maintainers (@bguillot is one).
* On the other side, I'm not sure that being in the OCA's umbrella will bring more maintainers. Wearing my OCA's contributor hat, I'm not sure that the OCA should disperse on more satellite projects when we are already have trouble to maintain the Odoo addons

Just some thoughts.

**Comment by pedrobaeza** [comment]
OK, you're right about the contributors question. It would be great then if you can add @sergio-teruel and me to the org. A mention in the OCA connector-prestashop repository will also help (We'll do it in our PR)

**Comment by pycode-biz** [comment]
@guewen  if you want help with maintain this project - add us to the org. 
If you have any questions please contact me at : info@pycode.biz
